### ISSUE TITLE
Ik kan een gepubliceerde entity bewerken

### ISSUE THREAD

**Issue by phavekes** [SURFnet/sp-dashboard#1005]
[This issue is imported from pivotal - Originaly created at Nov 2, 2020 by Bart Geesink](https://www.pivotaltracker.com/story/show/175535045)

Als een entity op prod is gepubliceerd kan ik nog steeds "edit" acties uitvoeren. Dat mag alleen wanneer "coin:exclude_from_push" aanstaat

**Comment by phavekes** [comment]
The publication state for the detail screen was not handled correctly. As of: https://github.com/SURFnet/sp-dashboard/pull/390 they now share the determination logic between them. (Michiel Kodde - Nov 3, 2020)

**Comment by phavekes** [comment]
Deze versie leidt tot hetvolgende probleem:

Fatal error: Uncaught OutOfBoundsException: Required package "ocramius/proxy-manager" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files in /var/www/html/vendor/ocramius/package-versions/src/PackageVersions/FallbackVersions.php:46 Stack trace: #0 /var/www/html/vendor/ocramius/package-versions/src/PackageVersions/Versions.php(28): PackageVersions\FallbackVersions::getVersion(\'ocramius/proxy-...\') #1 /var/www/html/vendor/ocramius/proxy-manager/src/ProxyManager/Version.php(36): PackageVersions\Versions::getVersion(\'ocramius/proxy-...\') #2 /var/www/html/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php(131): ProxyManager\Version::getVersion() #3 /var/www/html/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php(107): Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper::getProxyManagerVersion() #4 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php(413): in /var/www/html/vendor/ocramius/package-versions/src/PackageVersions/FallbackVersions.php on line 46 (Bart Geesink - Nov 5, 2020)

**Comment by phavekes** [comment]
Gaat nu goed, maar ik heb nog een oidcng entity waar het de edit knop wel te zien is in het entity detail window, maar ik daarna een access denied krijg als ik erop klik (dus de beveiliging zit goed) (Bart Geesink - Nov 5, 2020)
